### ISSUE TITLE
bug(gatsby-plugin-fastify): SSR fallback routes do not work

### ISSUE THREAD

**Issue by tsdexter** [gatsby-uc/plugins#228]
## Describe the bug

Regular Gatsby SSR routes work fine but SSR fallback routes (as documented here: https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#collection-route--fallback) do not work on the fastify server (they do in dev and gatsbycloud)

## To Reproduce

1. Create some File System Routing API pages from your CMS data `pages/{nodeType.uri}.tsx` where the URI may included a nested page structure such as `/nested/some-page` 
2. Create an SSR fallback route like `pages/nested/[slug].tsx` which should be used for any uri such as `/nested/this-page-does-not-exist-in-the-cms` so the data can be sourced from the CMS (or elsewhere) at runtime to see if it does in fact exist

Reproduction: https://github.com/tsdexter/gatsby-fastify-ssrrepro
Fallback route **does not** work on a fastify server: https://hxquaxlw4hzlpgivnrnsslv5c.js.wpenginepowered.com/ 

Notice when you click the link to 'SSR Fallback Page' (`/nested/fallback`) it returns a 404 error

## Expected behavior

Fallback route **does** work on gatsbycloud (and during `npm run develop`): https://gatsbyfastifyssrrepromaster.gatsbyjs.io/ 

Notice when you click the 'SSR Fallback Page' (`/nested/fallback`) the page does load and in the content area outputs the `slug` param that was passed from the server - note: you can also browse to any slug in the `/nested/*` path and it will load as well, ie: https://gatsbyfastifyssrrepromaster.gatsbyjs.io/nested/any-possible-slug

## System Info

Please provide information about your site via these means as possible:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.5 - /c/Python310/python
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
  npmPackages:
    gatsby: ^4.19.1 => 4.19.1 
    gatsby-plugin-fastify: ^0.8.1 => 0.8.1 
  npmGlobalPackages:
    gatsby-cli: 4.18.1

**Comment by tsdexter** [comment]
@moonmeister if you can point me in the right direction, I'm open to submitting a PR, time permitting

**Comment by moonmeister** [comment]
https://github.com/gatsby-uc/plugins/tree/main/packages%2Fgatsby-plugin-fastify%2Fsrc%2Fplugins contains the server routing plugin and the client only routes plugin. Not sure which is the culprit, but I'd start there, probably with client only routes. 

If that's a newer feature, or really either way, I often go find the code for Gatsby's dev server to use as a reference for the basics how to implement, just translated to fastify from express. 

If you have specific questions I can do my best to answer.

**Comment by moonmeister** [comment]
@tsdexter You have any luck with this?

**Comment by tsdexter** [comment]
@moonmeister I've had to work on other more crucial features since but we still need this working for launch, so I will have to come back to it eventually if someone else doesn't get to it first.

**Comment by moonmeister** [comment]
Fixed in #253
