### ISSUE TITLE
feat(gatsby-plugin-fastify): add support for fastify `caseSensitive` option

### ISSUE THREAD

**Issue by tsdexter** [gatsby-uc/plugins#268]
## Is your feature request related to a problem? Please describe.

Gatsby is often used with Wordpress. Wordpress does not follow RFC spec for case sensitivity in URLs (hence on a typical wordpress site, any casing in your URL will return the expected page and users are accustomed to this). Fastify URLs are case sensitive by default. Incorrectly cased URLs pointing at Wordpress sites do not work with this plugin. Unfortunately, this cannot always be controlled as the URLs may exist in third party systems.

## Describe the solution you'd like

Either add support for configuration of Fastify `caseSensitive` option https://www.fastify.io/docs/latest/Reference/Server/#casesensitive or enable it by default.

## Describe alternatives you've considered

I've currently worked around the issue by modifying my 404 page to add a frontend redirect, but it is far from ideal and causes a `FOF0FC` (like a `FOUC` but with 404 content). This results in the incorrectly cased URLs hitting the 404 page, redirecting to an all lowercase version to see if it's a real 404 or a casing issue, then they either get the correct page or 404 again. 

```
const NotFoundPage = (): JSX.Element => {
  const [loading, setLoading] = React.useState(true)
  React.useEffect(() => {
    // hacky workaround for case sensitive URLs
    if (typeof window !== `undefined`) {
      const { pathname } = window.location
      const lowerPathname = pathname.toLowerCase()
      if (lowerPathname !== pathname) {
        window.location.replace(lowerPathname)
      } else {
        setLoading(false)
      }
    }
  }, [])
  return (
    <MainLayout breadcrumbs={null} localMenuItem={null} minHeight={false}>
      {loading ? (
        <div>Hang tight we're looking for that page!</div>
      ) : (
        <div className="main-container border-none">
          <h1>404 not found</h1>
          <p>The page you are looking for cannot be found</p>
          <p>
            Lost? Start over at our <Link to="/">home page</Link>
          </p>
        </div>
      )}
    </MainLayout>
  )
}
```

**Comment by moonmeister** [comment]
This makes sense, you interested in contributing a PR?

**Comment by tsdexter** [comment]
@moonmeister enabling it by default, I can probably add pretty quick...but I assume you would prefer a configuration option? That'll take me a little more digging through the code, writing tests etc... Still willing to add it, but we're currently prepping for launch early Nov. and have a decent backlog from UAT results so it'll take me a few weeks minimum, if not longer.

**Comment by moonmeister** [comment]
If I get a chance I'll implement this...I might actually just implement the ability to override any Fastify server config instead of just this setting so folks can tweak as needed.

**Comment by tsdexter** [comment]
@moonmeister  That would be ideal, and I'd really appreciate it. 

While you're in there, if it's not much extra work, I also need the ability to send custom headers for SSG routes - not sure how much work that would be. 

I was looking into a PR to essentially have an env var `process.env.NEVER_CACHE_HEADER` that you could set to replace the value of the existing `NEVER_CACHE_HEADER` constant, but again an option for configuring all headers instead of just the `cache-control` and even a different option for each route type (or individual route) would be a more ideal way. For example, I also need a way to set `content-security-policy` header

**Comment by moonmeister** [comment]
> @moonmeister  That would be ideal, and I'd really appreciate it. 
> 
> While you're in there, if it's not much extra work, I also need the ability to send custom headers for SSG routes - not sure how much work that would be. 
> 
> I was looking into a PR to essentially have an env var `process.env.NEVER_CACHE_HEADER` that you could set to replace the value of the existing `NEVER_CACHE_HEADER` constant, but again an option for configuring all headers instead of just the `cache-control` and even a different option for each route type (or individual route) would be a more ideal way. For example, I also need a way to set `content-security-policy` header 
> 
> 

I think I have a half baked PR or branch for this somewhere....🤔

**Comment by tsdexter** [comment]
@moonmeister nice, that looks pretty extensive - would have taken me quite some time to figure that out..do you think it's far from completion or that it even still works now that fastify is at 4.x?

**Comment by moonmeister** [comment]
No idea, it's very stale.
