### ISSUE TITLE
bug(gatsby-plugin-fastify): Client-only route that also uses getServerData is not working

### ISSUE THREAD

**Issue by denisgoryaynov** [gatsby-uc/plugins#289]
## Describe the bug

I created a client-only route inside `src/pages/community/[...].tsx` and following the gatsby documentation I exported a component containing a `Router` and some routes accessible only by registered users.

The problem I am facing is caused by adding `getServerData` to this page.
Even if the sub-routes of this page are accessible only by registered users I still have some data that should be fetched during `ssr` to configure the page and some of the sections it contains.

This line of code is what is causing the problem:
https://github.com/gatsby-uc/plugins/blob/a01b1aee2fb6f1bf8d113abb83b573d36a6f6218/packages/gatsby-plugin-fastify/src/gatsby/clientSideRoutes.ts#L12

Since client-only routes are registered only if they are not SSR or DSG, my page is not getting registered and I run into 404s when visiting any page under /community.

Should this line check for page?.matchPath?.endsWith('*') to register client routes instead?

## System Info

System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Safari: 16.1
  npmPackages:
    gatsby: ^4.24.6 => 4.24.6
    gatsby-plugin-fastify: ^0.9.5 => 0.9.5
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0
    gatsby-plugin-react-i18next: ^2.0.4 => 2.0.5
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-sass: ^5.24.0 => 5.24.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0

**Comment by moonmeister** [comment]
Hello and welcome! So we just shipped a patch for possibly the same issue in #253, have you updated to the latest version?

**Comment by denisgoryaynov** [comment]
Hi @moonmeister, thank you for your support!

I updated `gatsby-plugin-fastify` to the latest version 0.9.6. It seems to be able to handle my use case, but when I try to run the server it crashes with the following error: `error Error: Wildcard must be the last character in the route`.

It seems to be caused by the package `find-my-way` which is a dependency of fastify. I tried to add some logs before the line that throws that error (modifying directly the package inside node_modules) and it seems to be caused by calling this route `/page-data/community*/page-data.json`, which is the data that gatsby compiles for the page.

Deleting the `getServerData` block from `src/pages/community/[...].tsx` fixes the issue and I am able to run the server.

**Comment by starrett67** [comment]
This happens for me as well for my SSR page that is served on a matchpath

**Comment by moonmeister** [comment]
Sorry to hear you're running into an issue. 

Are you interested in contributing a fix? I'm not sure when I'll be able to get to this. I know this above suggestion is incorrect, as all SSR related code is in https://github.com/gatsby-uc/plugins/blob/main/packages/gatsby-plugin-fastify/src/plugins/serverRoutes.ts. 


If you aren't able to contribute a fix, to help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by starrett67** [comment]
Gonna try to dedicate some more time to this tomorrow!

**Comment by starrett67** [comment]
`Should this line check for page?.matchPath?.endsWith('*') to register client routes instead?`

I would not like this solution because I have an SSR page that is ending with *

**Comment by moonmeister** [comment]
Yeah that fix il incorrect as it would only affect client only routes, not SSR.

**Comment by moonmeister** [comment]
Think I know why this isn't working. Have a possible fix in the works.

**Comment by moonmeister** [comment]
ended up being able to reproduce...fix in the works.

**Comment by starrett67** [comment]
Hey, @moonmeister I tried the new version with the fix for this issue. I'm still seeing the same error on my end but I think its a slightly separate issue so I'm going to open another one shortly.

**Comment by starrett67** [comment]
False alarm! It actually is working I just had to do a fresh build. Thank you so much for fixing this @moonmeister

**Comment by moonmeister** [comment]
Yay! Yeah the fixes work during the Gatsby build so that makes sense!!
