### ISSUE TITLE
bug(gatsby-plugin-fastify): Splat route causing 404 page and duplication of pathPrefix

### ISSUE THREAD

**Issue by pea** [gatsby-uc/plugins#326]
## Describe the bug

Splat route not registering on client-side navigation and shows a 404 page. On a hard refresh path prefix is duplicated in url.

## To Reproduce

I've created a demo of the issue here: https://github.com/pea/gatsby-fastify

## Steps

1. Run https://github.com/pea/gatsby-fastify
2. Go to http://localhost:5000/uk/
3. Click on `One Product`
4. Observe 404 page
5. Hard refresh the page
6. Observe url is `http://localhost:5000/uk/uk/one-product` and the page reads `Slug: uk/one-product`

## Expected behavior

On hard refresh the url should remain `http://localhost:5000/uk/one-product` and the page should read `Slug: one-product`

## System Info

  System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0.1
    Safari: 16.1
  npmPackages:
    gatsby: ^4.25.0 => 4.25.0 
    gatsby-plugin-fastify: ^0.12.0 => 0.12.0 
  npmGlobalPackages:
    gatsby-cli: 5.2.0

**Comment by moonmeister** [comment]
Hey @pea! I was working on another feature a couple weeks back and think I actually ran across this and just assumed it was my new code breaking things. I'm not sure when I can get to this. Are you interested in making a PR to resolve and add tests?

**Comment by moonmeister** [comment]
With the announcement of the [Gatsby Adapters](https://github.com/gatsbyjs/gatsby/discussions/38231) spec, we'll be discontinuing any work on this plugin. Should the need for a performant node server still be needed, this work can continue under the official spec as `gatsby-adapter-fastify`.
