### ISSUE TITLE
add: gatsby-source-strapi

### ISSUE THREAD

**Issue by derrickmehaffy** [gatsby-uc/plugins#330]
### Plugin Repository

https://github.com/strapi/gatsby-source-strapi

### Plugin Package

https://www.npmjs.com/package/gatsby-source-strapi

### Plugin Description

Source plugin for pulling documents into Gatsby from a Strapi API.

### Further Details

Per our discussion on this issue: https://github.com/strapi/gatsby-source-strapi/issues/352#issuecomment-1353570294 I'm creating this issue as a formal intent to transfer ownership/maintainership of our plugin for Gatsby over to the GUC as our team (Strapi) can no longer dedicate time and resources to maintain it but there has been an expressed interest from our community members to assist in maintaining it.

**Comment by moonmeister** [comment]
Awesome!!

**Comment by derrickmehaffy** [comment]
I've contacted @alexandrebodin internally to see if we can get the repo transfered and add you to the NPM package.

Thanks again!

**Comment by laurenskling** [comment]
Thanks @derrickmehaffy will try to work on this asap

**Comment by jonadeline** [comment]
thank you guys 🧡 ! 
we are just about to launch a new magazine site using Gatsby with Strapi and that's a relief for us to see that this plugin will be maintained.

**Comment by derrickmehaffy** [comment]
Looks like the repo got transfered and we added @moonmeister to the npm package as a maintainer!

Thanks again to the Gatsby UC!

**Comment by moonmeister** [comment]
Thanks @derrickmehaffy !! I confirmed this morning. I'll probably get our side next week.
