### ISSUE TITLE
bug (gatsby-source-strapi): Build breaks trying to display RichText changes (richtext.data = null)

### ISSUE THREAD

**Issue by youmeokay** [gatsby-uc/plugins#338]
Hi there, 

I hope this is the right place to address this issues, maybe it has to do with another plugin I am using, currently not sure. So I start here, because I can't find anything on the web regarding this.

My problem is around previewing richtext content updates, AFTER they are initially filled. So in a single-type (/previewtest), I have a richtext-field and when I initially put content in there and hit the blue gatsby-preview button, the (incremental) build is fine and shows as deployed. All as intended.

But when I go back to Strapi and change the richtext field again (bold some text, or add another paragraph) and hit the preview button again, the build seems to be fine (Gatsbycloud says its built and deployed) but the preview shows as plain text and the console is throwing the following error;

`XHR GET https://preview-exampleproject.gtsb.io/usr/src/app/www/public/page-data/previewtest/page-data.json [HTTP/2 404 Not Found 520ms]`

`This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.`

```

Preview build error
There was an error when building the preview page for this page ("/previewtest/").

TypeError: Cannot read property 'richtext' of null
    at PreviewTest (/usr/src/app/www/.cache/page-ssr/routes/webpack:/exampleproject/src/pages/previewtest.js:17:43)
    at d (/usr/src/app/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/usr/src/app/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/usr/src/app/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/usr/src/app/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at renderToString (/usr/src/app/www/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.staticPage [as default] (/usr/src/app/www/.cache/page-ssr/routes/webpack:/exampleproject/.cache/static-entry.js:295:22)
    at _bluebird.default.map.concurrency (/usr/src/app/www/node_modules/gatsby/src/utils/worker/child/render-html.ts:162:11)
```

"previewtest" is my single-type which holds the richtext data.
"exampleproject" is my projectname in gatsby.

**Further information:**

It all works as intended, if I change any other field from that single-type (previewtest). With changes in media-fields and/or **non-html** text, it all builds a correct preview and shows the content changes in the frontend.

**Query:**

`{
    strapiPreviewtest {
      updatedAt
      headline
      richtext {
        data {
          id
          richtext
          childMarkdownRemark {
            html
          }
        }
      }
      image {
        alternativeText
        localFile {
          url
          childImageSharp {
            gatsbyImageData(aspectRatio: 1.7)
          }
        }
      }
    }
  }`

**frontend rendering:**

`<div dangerouslySetInnerHTML={{__html: previewtest.richtext.data.childMarkdownRemark.html}} />`

system: 
Strapi **v4.1.9** (heroku)
Gatsby **v4.13.0** (gatsby cloud)

(some) plugins I am using;
- gatsby-source-strapi 
- gatsby-transformer-remark
- strapi-plugin-gatsby-preview

Can someone point me towards the right direction? Is this a cache problem?
Does it has to do with the content-sync of gatsbycloud? Or strapi-chaching?
Or dangerouslySetInnerHTML? Thank you for any help on this.

**Comment by laurenskling** [comment]
This has been fixed at https://github.com/gatsby-uc/gatsby-source-strapi/pull/344
