### ISSUE TITLE
bug(gatsby-source-strapi): `content.data` is null when `lastFetched` exists

### ISSUE THREAD

**Issue by ohcmadah** [gatsby-uc/plugins#340]
Hi,

I have a richtext type `content` field. Everything was good when I build it for the first time without cache.
But I modified the `post` in Strapi and rebuilt it. Then the `content.data` of the `post` that I modified was **null**.

<img src="https://user-images.githubusercontent.com/52340070/158099098-d824ea0e-7337-4cf9-8722-9e05d6e9ec5e.png" alt="graphql" width="300" />

### version

gatsby `^4.7.2`
gatsby-source-strapi `2.0.0-beta.0`
Strapi `4.1.0`

**Comment by laurenskling** [comment]
Discussed in https://github.com/gatsby-uc/plugins/issues/338 and fixed in https://github.com/gatsby-uc/gatsby-source-strapi/pull/344
