### ISSUE TITLE
feat(gatsby-source-strapi): Support plugin prefixes

### ISSUE THREAD

**Issue by mwoelk** [gatsby-uc/plugins#342]
Plugins such as `i18n` include their own content types such as `locale` that can be queried via the api as well.
Those are exposed on sub paths of the form `/api/{plugin}/{pluralName}`.

When trying to fetch e.g. the `locale` type, currently the request is made to `/api/locales` as it is resolved through the fetched schema but the plugin prefix is not used although it can be derived from the `plugin` field in the schema.

**Why is this useful?**
Especially in the example case with locales, it can be used to query a list of all locales and their names in order to build e.g. a language switcher component.

**Comment by laurenskling** [comment]
This has been fixed in https://github.com/gatsby-uc/gatsby-source-strapi/pull/289
