### ISSUE TITLE
feat(gatsby-source-strapi): Graphql filter on one type doesn't work

### ISSUE THREAD

**Issue by mariovde-IIO** [gatsby-uc/plugins#343]
Hi,

Question:
I use the queries below in the gatsby-graphql playground.
When I use the current query:

```
query MyQuery {
  allStrapiJob(filter: {data: {elemMatch: {id: {eq: 2}}}}) {
    nodes {
      data {
        attributes {
          slug
          title
        }
        id
      }
      id
    }
  }
}
```

I get this as a result

```
{
  "data": {
    "allStrapiJob": {
      "nodes": [
        {
          "data": [
            {
              "attributes": {
                "slug": "helpdesk-engineer-uk",
                "title": "Helpdesk Engineer"
              },
              "id": 1
            },
            {
              "attributes": {
                "slug": "frontend-developer",
                "title": "Frontend developer"
              },
              "id": 2
            }
          ],
          "id": "Job_undefined"
        }
      ]
    }
  },
  "extensions": {}
}
```
Always 2 results (there are 2 entries in strapi at the moment)
If I change the id to filter, to either 1 or 2, I always get 2 results.
When changing it to anything else then 1 or 2, I get nothing as a result.

What am I doing wrong here?

Also, I got "strapiJob" to use.

```
query MyQuery {
  strapiJob(data: {elemMatch: {id: {eq: 1}}}) {
    data {
      attributes {
        slug
        title
        description
      }
      id
    }
  }
}
```

Same result, always 2 entries.

**Comment by laurenskling** [comment]
I am assuming this is Strapi 4 data fetched (because of the `.data.attributes` blocks) by version 1 of `gatsby-source-strapi` which only supports Strapi 3.  Please create a new issue with new info if you think otherwise.
