### ISSUE TITLE
feat(gatsby-source-strapi): Add support for MDX

### ISSUE THREAD

**Issue by jan-wagenaar** [gatsby-uc/plugins#347]
In earlier versions of gatsby-source-strapi, MDX was supported (or rather just working). This meant we can use more sophisticated markdown syntax. This was really nice to add custom components (like Expo Snack viewer in my case). Currently I switched back [gatsby-transformer-remark](https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/), which works but has less functionality. I would like to use gatsby-plugin-mdx's Nodes on rich text fields in GraphQL
 
Please add MDX support through gatsby-plugin-mdx.

**Comment by laurenskling** [comment]
You could submit a PR to allow both `remark` and `mdx` to work.

**Comment by laurenskling** [comment]
Any type of contribution is welcome. If you can try to find why MDX is not supported and how we can make it so, we can try to create a feature for it together.

**Comment by jan-wagenaar** [comment]
I've been looking into it. It's not the issue with this strapi plugin, but rather that gatsby-plugin-mdx stopped supporting transformations of GraphQL fields. Saw in their [plugin documentation](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#migrating-from-v3-to-v4) this sentence: 

> Please Note: Loading MDX from other sources as the file system is not yet supported in gatsby-plugin-mdx@^4.0.0.

So starting from this plugin version, only file based MDX is supported.. I will need to look into a different solution. Guess there are two ways to overcome this: 

- Create the file nodes for every markdown content field and let MDX process those
- Find a different package which is able to handle a MDX string. This seems to be a bit harder though.

However, will close this issue since it's out of scope of the strapi plugin.

**Comment by moonmeister** [comment]
Good find, yeah, based on what I know I suspected something like this, I suppose the 3rd option is to work on contributing this transform feature upstream into `gatsby-plugin-mdx`.

**Comment by konsalex** [comment]
Also I think this page could be updated to avoid future confusion with Gatsby v5 users: https://www.gatsbyjs.com/plugins/gatsby-source-strapi/#rich-text-field 📝 Nice finding @jan-wagenaar

**Comment by laurenskling** [comment]
@konsalex what do you believe to be confusing about that piece of documentation?

**Comment by konsalex** [comment]
That it does not work with current Strapi v4 and Gatsby v5 @laurenskling or am I missing something? 

I would assume that the fact that I am missing the `body` and `childMarkdownRemark` property is related to this issue.

**Comment by laurenskling** [comment]
No it is not related. This topic is about MDX, not markdown. Please open a new issue for this. And please show the schema for `features.description`
