### ISSUE TITLE
bug(*): Missing `index.js` 

### ISSUE THREAD

**Issue by moonmeister** [gatsby-uc/plugins#349]
> What's the error with index.js? Cause none of the other plugins have that file.

As I said, it gives 

```
Couldn't find the "gatsby-source-strapi" plugin declared in "/Users/laurenskling/sites/gatsby-monorepo/packages/gatsby-theme-core/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /Users/laurenskling/sites/gatsby-monorepo/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/gatsby-monorepo/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/gatsby-monorepo/node_modules/gatsby/dist/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/gatsby-monorepo/node_modules/gatsby/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/gatsby-monorepo/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/node_modules/gatsby-source-strapi
 - /Users/laurenskling/node_modules/gatsby-source-strapi
 - /Users/node_modules/gatsby-source-strapi
 - /node_modules/gatsby-source-strapi
```

I don't know why. `filesystem` and `wordpress` also have it. I saw `s3` doesn't have it. No idea how Gatsby tries to find the plugin. I don't see the difference.

_Originally posted by @laurenskling in https://github.com/gatsby-uc/plugins/issues/345#issuecomment-1366807447_

**Comment by moonmeister** [comment]
@laurenskling I installed a basic Gatsby site with `npm install gatsby` and added the plugin. I checked `node_modules` my suspicions were wrong, all the build files are there correctly. I added the plugin to `gatsby-config.js` manually with no `options` and running development correctly finds the plugin, It fails to fetch data (as it should since I haven't provided URL or API keys. 


Basically, I can't reproduce this issue. Can you work on minimal reproduction? What's different? Are you using this in a theme? Are you using a different package manager?

**Comment by moonmeister** [comment]
UPDATE: Moving here so we can confirm bug and create a reproduction and ship the options fix in the meantime.

**Comment by laurenskling** [comment]
@moonmeister , since the code I found the crash in was in `load-themes`, I guess you need to run your project with themes for it to happen? Did you have themes installed?

**Comment by laurenskling** [comment]
Using `yarn` and `node 18`

**Comment by moonmeister** [comment]
I didn't, please create a reproduction.

Dec 29, 2022 11:27:53 AM Laurens Kling ***@***.***>:

**Comment by laurenskling** [comment]
for reference: https://github.com/gatsbyjs/gatsby/discussions/37344

**Comment by laurenskling** [comment]
Ah it happens specifically when `gatsby-source-strapi` is a plugin _of_ a theme. (which in my case is true, i run source-strapi from my own `gatsby-theme-core`)

```
> gatsby develop

success compile gatsby files - 0.293s

 ERROR #10226  API.CONFIG.LOADING

Couldn't find the "gatsby-source-strapi" plugin declared in
"/Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/@lekoarts/gatsby-theme-emma/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/gatsby/dist/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/gatsby/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/test/gatsby-starter-portfolio-emma/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/test/node_modules/gatsby-source-strapi
 - /Users/laurenskling/sites/node_modules/gatsby-source-strapi
 - /Users/laurenskling/node_modules/gatsby-source-strapi
 - /Users/node_modules/gatsby-source-strapi
 - /node_modules/gatsby-source-strapi

not finished load gatsby config - 0.026s
```

reproduction steps:
1. npx gatsby new gatsby-starter-portfolio-emma https://github.com/LekoArts/gatsby-starter-portfolio-emma
2. yarn/npm add `gatsby-source-strapi`
3. in ./node_modules/@lekoarts/gatsby-theme-emma/gatsby-config.js add `gatsby-source-strapi` to the plugins

It will now crash on this line: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-themes/index.ts#L63

**Comment by moonmeister** [comment]
Thanks! Nice find! This will need to be fixed with all plugins then. Would you like to fix now or wait for the response on that issue?

**Comment by laurenskling** [comment]
We can fix now for all I guess. I found it hard to believe all gatsby sources had the noop file without it having use.

**Comment by laurenskling** [comment]
And all of a sudden, a very old memory came crawling up from the back of my brain.
https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/building-themes/#gatsby-theme-minimal
index.js is required in themes, according to this documentation. So actually, it's not only themes, but all plugins within themes as well. 

We can use the Gatsby discussion thread to discuss with the team about what this means for all plugins in themes.

**Comment by laurenskling** [comment]
Just did a quick test, `gatsby-plugin-pinterest` will also fail to load when it's a plugin in a theme. So yes, we need to add to all. You want me to do it? How to go about with the `no-empty-file` lint? ignore `packages/**/index.js`?

**Comment by moonmeister** [comment]
Strange. Til. 🤷‍♂️ Let's add them all back and add the ignore favor all index.js files in package root. You want to or should I?

**Comment by laurenskling** [comment]
Haha great minds think alike ;) If you could do it, that would be cool. Im pretty sure we have the same idea.
