### ISSUE TITLE
add[gatsby-source-airtable]

### ISSUE THREAD

**Issue by moonmeister** [gatsby-uc/plugins#368]
### Plugin Repository

https://github.com/jbolda/gatsby-source-airtable

### Plugin Package

https://www.npmjs.com/package/gatsby-source-airtable

### Plugin Description

Sources data from Airtable. 

### Further Details

https://github.com/gatsby-uc/plugins/discussions/367

Chatted with @jbolda and he's busy on other projects and has previously tried to get Gatsby and Airtable to take over this important plugin. They've both declined and Jacob is happy to have it find a home here in the GUC. 

#### Contributor Tasks: 
- [x] [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) to the `gatsby-uc` 
- [x] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

#### Admin 
- [x] Move code into `gatsby-uc/plugins` repo
- [x] Update Readme in old repo to redirect folks to new location using [template](https://github.com/gatsby-uc/plugins/blob/main/templates/old_repo_readme.
- [x] Move/Comment on still applicable PRs/
- [ ] Archive old 
- [ ] Update Plugin with [best practices](https://github.com/gatsby-uc/plugins/blob/main/CONTRIBUTING.md#plugin-best-
- [ ] Publish new version

**Comment by jbolda** [comment]
We have discussed a few modifications on the default steps. I am going to open a PR directly to the monorepo to bring in the commits from the previous repository to maintain the history. With that, I can add a commit to make a few adjustments per best practices and having the `package.json` match the new location.

Is there a need for the previous repo to be transferred? I am fine closing things out, transferring anything worthwhile, and archiving the repo.

Also, is it worthwhile having a GUC npm user? Or is there a GUC organization and I am misunderstanding the docs?

**Comment by davidpaulsson** [comment]
I have this plugin as well, https://github.com/davidpaulsson/gatsby-source-airtable-next, happy to help migrate some or all of that codebaseI ideas to this namespace

**Comment by moonmeister** [comment]
> I have this plugin as well, https://github.com/davidpaulsson/gatsby-source-airtable-next, happy to help migrate some or all of that codebase/ideas to this namespace

@davidpaulsson Hey! One of my goals with the Gatsby UC is to help reduce the number of "duplicate" plugins. If you open your own issue to add a plugin we can chat about it more there. TL;DR, Once this plugin is in we can review the differences, see if there's a path forward for merging, and how we'll do so

**Comment by moonmeister** [comment]
> We have discussed a few modifications on the default steps. I am going to open a PR directly to the monorepo to bring in the commits from the previous repository to maintain the history. With that, I can add a commit to make a few adjustments per best practices and having the `package.json` match the new location.
>
> Is there a need for the previous repo to be transferred? I am fine closing things out, transferring anything worthwhile, and archiving the repo.

Probably not, I've done that cause I'm usually the one doing the work on the old repo, and its easier to find if we want to see git history, but now that you're merging that into our repo...doesn't seem necessary. 

> Also, is it worthwhile having a GUC npm user? Or is there a GUC organization and I am misunderstanding the docs?

We don't have a GUC user, there is a GUC org that I'll add the plugin to but npm doesn't give permissions to orgs, they give it to users. Hence why you need to add my npm account. It's my api key that authenticates the deploys. If there is a better way I'm happy to take suggestions. 

> There are also a handful of example sites / integration tests. It looks like there is an `integration-tests` folder. Should I add a `source-airtable` folder there an add each as a subfolder within it?

If you have a dedicated gatsby site for testing, yes, that's where we've been putting the sites. the tests themselves usually live with the package. Again, open to suggestions here. 

Finally, I know I've written docs, if you see anything specific that is confusing or I contradict, please let me know, many of those were written before any actual work as a theoretical process.

**Comment by jbolda** [comment]
> We don't have a GUC user, there is a GUC org that I'll add the plugin to but npm doesn't give permissions to orgs, they give it to users. Hence why you need to add my npm account. It's my api key that authenticates the deploys. If there is a better way I'm happy to take suggestions.

In the handful of orgs that I have been involved with / setup CI, we have made a new npm user specific for that use case. I don't feel that it is a hard blocker, but moreso a suggestion.
