### ISSUE TITLE
bug(gatsby-source-strapi): Markdown content not processed

### ISSUE THREAD

**Issue by konsalex** [gatsby-uc/plugins#391]
## Describe the bug

Continuing the thread from here: https://github.com/gatsby-uc/plugins/issues/347#issuecomment-1460031944

Markdown nodes are not processed with [`gatsby-transformer-remark`](https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/).

## To Reproduce

The schema of the description is:

```graphql
type STRAPI__COMPONENT_PRICING_FEATUREDescription {
  data: STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE
}

type STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE implements Node {
  children: [Node!]!
  description: String
  id: ID!
  internal: Internal!
  parent: Node
}
```

and media type:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12672541/223719539-9f3a30e6-49e8-4f68-aadb-312f5654fc84.png">

## Expected behavior

To include as docs state:

```
data {
          # unprocessed data from Strapi
          body
          # processed markdown
          childMarkdownRemark {
            html
            rawMarkdownBody
          }
```

## System Info

```bash
  System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /private/var/folders/9l/60kxtcz13776cgxqhgjhh0v40000gn/T/xfs-268e643c/node
    Yarn: 3.4.1 - /private/var/folders/9l/60kxtcz13776cgxqhgjhh0v40000gn/T/xfs-268e643c/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/79408_1678276889248/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    gatsby: ^5.6.0 => 5.7.0 
    gatsby-plugin-algolia: ^1.0.3 => 1.0.3 
    gatsby-plugin-canonical-urls: ^5.6.0 => 5.7.0 
    gatsby-plugin-catch-links: ^5.6.0 => 5.7.0 
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.6 
    gatsby-plugin-graphql-codegen: ^3.0.0 => 3.1.1 
    gatsby-plugin-image: ^3.6.0 => 3.7.0 
    gatsby-plugin-manifest: ^5.6.0 => 5.7.0 
    gatsby-plugin-mdx: ^5.7.0 => 5.7.0 
    gatsby-plugin-next-seo: ^1.10.0 => 1.10.0 
    gatsby-plugin-offline: ^4.4.0 => 4.15.0 
    gatsby-plugin-portal: ^1.0.7 => 1.0.7 
    gatsby-plugin-postcss: ^6.6.0 => 6.7.0 
    gatsby-plugin-preact: ^7.7.0 => 7.7.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.15.0 
    gatsby-plugin-sass: ^6.6.0 => 6.7.0 
    gatsby-plugin-sharp: ^5.6.0 => 5.7.0 
    gatsby-plugin-sitemap: ^6.6.0 => 6.7.0 
    gatsby-remark-autolink-headers: ^6.6.0 => 6.7.0 
    gatsby-remark-embed-video: ^3.1.1 => 3.2.1 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^5.10.0 => 5.12.0 
    gatsby-remark-images-anywhere: ^1.3.1 => 1.3.1 
    gatsby-remark-responsive-iframe: ^6.6.0 => 6.7.0 
    gatsby-remark-smartypants: ^6.6.0 => 6.7.0 
    gatsby-source-filesystem: ^5.7.0 => 5.7.0 
    gatsby-source-strapi: ^3.0.4 => 3.0.4 
    gatsby-transformer-sharp: ^5.6.0 => 5.7.0 
```

**Comment by laurenskling** [comment]
Did you create the types yourself?
try this, this is how I type it myself:
```
type STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE implements Node {
  childMarkdownRemark: MarkdownRemark
}
type STRAPI__COMPONENT_PRICING_FEATUREDescription {
  data: STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE @link(by: "id", from: "data___NODE")
}
```

**Comment by konsalex** [comment]
@laurenskling not those types are not created by me. The types are generated by `gatsby-source-strapi` and the following is from the generated schema:

```graphql
type STRAPI__COMPONENT_PRICING_FEATUREDescription {
  data: STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE
}

type STRAPI__COMPONENT_PRICING_FEATURE_DESCRIPTION_TEXTNODE implements Node {
  children: [Node!]!
  description: String
  id: ID!
  internal: Internal!
  parent: Node
}
```

**Comment by laurenskling** [comment]
I don't know what to say mate. It should just work. It makes a TEXTNODE and everything.. just missing the 
```
childrenMarkdownRemark: [MarkdownRemark]
childMarkdownRemark: MarkdownRemark
```
fields. Is this the only field where there is no markdown, or do you not see any?
I think it's `gatsby-source-filesystem` that adds the markdown support right? Did you include that in your plugins config?

**Comment by laurenskling** [comment]
@konsalex I just ran into the fact that one of my websites is starting to return `data: String` on one of my richtext. Super weird.. For some reason, the content isn't linked. Because, it is there. Can you try to query:

```
query {
  allStrapiComponentPricingFeatureDescriptionTextnode {
    nodes {
      id
      childMarkdownRemark {
        id
        html
      }
    }
  }
}
```
(maybe allStrapiComponentPricingFeatureDescriptionTextnode is spelled slighty different, try to find it in the docs explorer)

**Comment by konsalex** [comment]
@laurenskling in the `TextNode` still does not exist:

<img width="1502" alt="CleanShot 2023-03-23 at 22 58 44@2x" src="https://user-images.githubusercontent.com/12672541/227358907-a7284f69-8431-4407-8502-113db04c1227.png">

But found out that I was using an old version of `remark` plugin, so maybe that was causing the issue, curious why it did not throw 🤔  Now works as expected @laurenskling  thanks for looking into this

**Comment by laurenskling** [comment]
Glad it worked for you. Now I'm just stuck with my own bug haha. Will close this and create a new one.
