### ISSUE TITLE
bug(gatsby-plugin-fastify): all reverse proxy redirects end up as wildcards

### ISSUE THREAD

**Issue by tsdexter** [gatsby-uc/plugins#400]
## Describe the bug

When configuring Reverse Proxy redirects, they will be configured as a wildcard reverse proxy whether or not you include a `*` in the redirect `fromPath`.

## To Reproduce

Bug is reproduced in the repos test site at `gatsby-uc\plugins\integration-tests\plugin-fastify`

```js
  createRedirect({
    fromPath: "/example-proxy",
    toPath: "http://example.com",
    statusCode: 200,
  });

  createRedirect({
    fromPath: "/example-proxy-star/*",
    toPath: "http://example.com/*",
    statusCode: 200,
  });
```

## Expected behavior

All expected behaviour below can be demonstrated on Gatsby cloud site, ie: https://pluginsfeatfastifydefaultcusto.gatsbyjs.io/example-proxy-star/ or configuring above redirects and pushing to gatsby cloud. Actual behaviour can be tested in localhost using `npm start`/`gserve` with the above configured redirects in place. 

- `/example-proxy-star`, `/example-proxy-star/`
  - should respond `200` and serve `example.com` page
  - **ACTUAL BEHAVIOUR**: responds correctly ✔
- `/example-proxy-star/anything-else`
  - should respond with `404` from `example.com` and serve the `example.com` page
  - **ACTUAL BEHAVIOUR**: responds correctly ✔
- `/example-proxy`, `/example-proxy/`
  - should respond `200` and serve `example.com`
  - **ACTUAL BEHAVIOUR**: responds correctly ✔
- `/example-proxy-anything-else`
  - should respond with `404` from gatsby site and serve gatsby site 404 page 
  - **ACTUAL BEHAVIOUR**: responds correctly ✔
- `/example-proxy/anything-else`
  - should respond with `404` from gatsby site and serve gatsby site 404 page 
  - **ACTUAL BEHAVIOUR**: responds `404` from `example.com` and serves `example.com` page ❌

## Additional Info

I discovered this working on #392 and will have the fix committed there, just wanted to track it as a separate issue as well.

**Comment by moonmeister** [comment]
thanks! If we can put it in a separate PR that'd be great.

**Comment by tsdexter** [comment]
> thanks! If we can put it in a separate PR that'd be great.

will extract it Monday morning

**Comment by tsdexter** [comment]
> thanks! If we can put it in a separate PR that'd be great.

https://github.com/gatsby-uc/plugins/pull/401

**Comment by moonmeister** [comment]
With the announcement of the [Gatsby Adapters](https://github.com/gatsbyjs/gatsby/discussions/38231) spec, we'll be discontinuing any work on this plugin. Should the need for a performant node server still be needed, this work can continue under the official spec as `gatsby-adapter-fastify`.
