### ISSUE TITLE
bug(gatsby-source-strapi): Request failed with status code 500

### ISSUE THREAD

**Issue by xSyki** [gatsby-uc/plugins#410]
## Describe the bug
Once in a while while building I get a status of 500, when I try again it disappears, but it is very annoying. Together with the error, information should go what exactly failed and what url returned 500.

```bash
 ERROR #11321  API.NODE.EXECUTION
"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:
Request failed with status code 500
[G
  Error: Request failed with status code 500
[Gnot finished source and transform nodes - 24.886s
error Command failed with exit code 1.
```

Of course, I checked the logs in strapi and there is no request with a response of 500.

## Expected behavior

The error should contain information which url got the status 500.

### Code
From what I see in the fetch.js file, the lines responsible for reporting this are commented out, what is the reason for this?

```js
  } catch {
    // reporter.panic(
    //   `Failed to fetch data from Strapi ${opts.url} with ${JSON.stringify(opts)}`,
    //   error,
    // );
    return [];
  }
```

**Comment by laurenskling** [comment]
The reason for that is that a refetch of a single returns a 404 (🤷 ). 
If hit this myself in the past: https://github.com/gatsby-uc/plugins/issues/337

If you want to make a PR, I'd be happy to review it.

**Comment by laurenskling** [comment]
From what I read, you are actually hitting a 500 panic. Is that a collectionType? It might be handled correctly there. We could extend the logs about the error but im pretty sure your production strapi would just say `internal server error`. There should be logs in your strapi.
Logging _which_ endpoint errored would be good tho.

**Comment by xSyki** [comment]
@laurenskling Pull request submitted

**Comment by Volemon** [comment]
We actually managed to solve the issue with errors 500.
The problem was related to linux/nginx config:
1. worker_rlimit_nofile and worker_connections in nginx
2 configure ulimit properly so nginx will be able to work with multiple (a lot of) open files.
