### ISSUE TITLE
bug(gatsby-source-strapi): queryLimit breaks incremental build

### ISSUE THREAD

**Issue by mrkariox** [gatsby-uc/plugins#423]
## Describe the bug

`{
            singularName: 'review',
            queryLimit: 25,
            queryParams: {
              publicationState: process.env.GATSBY_IS_PREVIEW === 'true' ? 'preview' : 'live',
              populate: 'deep',
            },
          },`

If we set queryLimit in strapi-source plugin then gatsby fetches page data in "per page" basis:

info Starting to fetch data from Strapi - /api/reviews with "publicationState=preview&populate=deep&pagination[pageSize]=25&pagination[page]=2"
info Starting to fetch data from Strapi - /api/reviews with "publicationState=preview&populate=deep&pagination[pageSize]=25&pagination[page]=3"
info Starting to fetch data from Strapi - /api/reviews with "publicationState=preview&populate=deep&pagination[pageSize]=25&pagination[page]=4"
info Starting to fetch data from Strapi - /api/reviews with "publicationState=preview&populate=deep&pagination[pageSize]=25&pagination[page]=5"
info Starting to fetch data from Strapi - /api/reviews with "publicationState=preview&populate=deep&pagination[pageSize]=25&pagination[page]=6"

but when gatsby compares it with date (filters: updatedAt) it only checks last page not all of them:

info Starting to fetch data from Strapi - /api/reviews with {"publicationState":"preview","populate":"deep","pagination":{"pageSize":25,"page":6},"filters":{"updatedAt":{"$gt":1681409458879}}}

When i set "pageSize" in queryLimit to something big like 999999 when there is only one page looks like the page-data file updates correctly.

## To Reproduce

1. Set queryLimit to something like 25 (make sure you have more than 25 entries to create at least 2 pages
2. Build the page with gatsby build for the first time
3. Change entry that is on first page (any field from strapi)
4. Run build again without removing cache (to use incremental build)
5. See that page-data was not updated in public catalog

## Expected behavior

In incremental builds plugin compares all pages not only last page (with filters: updatedAt...) so the page-data file updates correctly.

## System Info

Please provide information about your site via these means as possible:

- strapi 4.4.5
- gatsby 4.23.0
- gatsby-source-strapi 3.0.6

**Comment by laurenskling** [comment]
We've fixed this a couple of releases ago. Are you on the latest version?

**Comment by mrkariox** [comment]
@laurenskling 
Tested on 3.0.6, when it was fixed? In which release? Thanks!

**Comment by laurenskling** [comment]
Check out the release notes :)

Op zo 30 apr. 2023 22:29 schreef Karol Bartkowski ***@***.***

**Comment by mrkariox** [comment]
fixed in version 3.1.0
