### ISSUE TITLE
bug(gatsby-plugin-fastify): `assetPrefix` Not Working

### ISSUE THREAD

**Issue by burakozdemir32** [gatsby-uc/plugins#434]
## Describe the bug

When I provide an `assetPrefix` for the Gatbsy application, the application is not built properly and all routes return 404.

## To Reproduce

1. Go to https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/asset-prefix/.
2. And follow steps to provide and asset prefix.
3. Build the application. (gatsby build --prefix-paths)
4. Run the application.
5. See 404.

## Expected behavior

The application is built properly considering the asset prefix.

## System Info

kerkenez | + yarn gserve
kerkenez | yarn run v1.22.19
kerkenez  | $ /app/node_modules/.bin/gserve
kerkenez  | {"level":30,"time":1686059638544,"pid":28,"hostname":"a54774706dcb","msg":"Logging Level set @ info"}
kerkenez | {"level":30,"time":1686059638544,"pid":28,"hostname":"a54774706dcb","msg":"Mounting Gatsby @ /"}
kerkenez | {"level":30,"time":1686059638551,"pid":28,"hostname":"a54774706dcb","msg":"Gatsby 500 error page exists"}
kerkenez | {"level":30,"time":1686059638754,"pid":28,"hostname":"a54774706dcb","msg":"Registering 1 client-only route(s)"}
kerkenez  | /bin/sh: lscpu: not found
kerkenez | {"level":30,"time":1686059638755,"pid":28,"hostname":"a54774706dcb","msg":"Registering 0 redirect(s)"}
kerkenez  | {"level":30,"time":1686059638756,"pid":28,"hostname":"a54774706dcb","msg":"Registering 0 reverse proxy route(s)"}
kerkenez | {"level":30,"time":1686059638757,"pid":28,"hostname":"a54774706dcb","msg":"Registering 0 DSG route(s)"}
kerkenez  | {"level":30,"time":1686059638757,"pid":28,"hostname":"a54774706dcb","msg":"Registering 3 SSR route(s)"}
kerkenez | {"level":30,"time":1686059639487,"pid":28,"hostname":"a54774706dcb","msg":"Gatsby 404 error page exists"}
kerkenez | {"level":30,"time":1686059639495,"pid":28,"hostname":"a54774706dcb","msg":"Server listening at http://0.0.0.0:8080"}

**Comment by moonmeister** [comment]
Hey! Yeah, this feature has not been implemented. I probably won't have time anytime soon to do so a PR, it would be welcome but this probably isn't an easy one. I'd have to give it some thought on how to accomplish this.

**Comment by burakozdemir32** [comment]
Thank you for the answer @moonmeister! I'd appreciate any PR or thoughts on how to proceed with the fix.

**Comment by moonmeister** [comment]
With the announcement of the [Gatsby Adapters](https://github.com/gatsbyjs/gatsby/discussions/38231) spec, we'll be discontinuing any work on this plugin. Should the need for a performant node server still be needed, this work can continue under the official spec as `gatsby-adapter-fastify`.
