### ISSUE TITLE
bug(gatsby-plugin-fastify): Error fetching page data for /using-ssr when pagePrefix is set

### ISSUE THREAD

**Issue by syckki** [gatsby-uc/plugins#458]
## The error happens when I use pathPrefix (e.g: /gatsby) in gatsby-config.js. I am serving SSR pages.

ERROR: Error processing /gatsby/page-data/using-ssr/page-data.json, Error fetching page data for /using-ssr: Page for "/gatsby/page-data/using-ssr/page-data.json" not found

## To Reproduce

1. Run the following boilerplate `npx gatsby new gatsby-starter-rendering-modes`
2. Add the following packages`npm install gatsby-plugin-fastify fastify`
3. Set pathPrefix (e.g: /gatsby) in gatsby-config.js
4. Add the plugin `plugins: [ { resolve: 'gatsby-plugin-fastify' }]` in gatsby-config.js,
5. Add the script `{ "scripts": { "start": "gserve" } }` in package.json
6. Run the command `npm run start`
7. The error appears in Console Tab

<img width="1996" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/798a9a00-f113-456e-94ee-8c3328551e2f">

A quick search in the gatsby-plugin-fastify code reveals me, the reason of the error. 

Use `potentialPagePath` instead of `workingURL` variable as `pathName` param in the `getData` method.
<img width="631" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/9249b3b0-9042-4b6f-80da-177abc73ce57">

[Additionally to solve problem with **trailingSlash**] 
Use `path` instead of `workingURL` variable as param of `reverseFixedPagePath` method.
<img width="624" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/687d7f90-77ea-471d-b1a2-30e49f7f8a3e">

## Expected behavior

A quick change in the compiled code solves the problem.

Code line 56 is modified to use the variable `potentialPagePath`.
<img width="667" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/190486cd-9ccf-424f-b236-d7685615f26c">

[Additionally to solve problem with **trailingSlash**] 
Code line 93 is modified to use the variable `path`.
<img width="685" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/379748aa-3472-496d-9eb7-bb3c5aa0b340">

eureka!!!

<img width="1675" alt="image" src="https://github.com/gatsby-uc/plugins/assets/14133177/8dc932d8-71a8-43f8-ad6a-3d52458621a3">

## System Info

- After running the command: `yarn gatsby info --clipboard` in my project directory

  System:
    OS: Windows 11 10.0.22621
    CPU: (4) x64 Apple Silicon
  Binaries:
    Node: 19.9.0 - C:\Users\JHONNY~1\AppData\Local\Temp\xfs-fea441dd\node.CMD
    Yarn: 4.0.2 - C:\Users\JHONNY~1\AppData\Local\Temp\xfs-fea441dd\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.12.0
  Browsers:
    Edge: Chromium (119.0.2151.97)
  npmPackages:
    gatsby: 5.12.12 => 5.12.12
    gatsby-plugin-alias-imports: 1.0.5 => 1.0.5
    gatsby-plugin-fastify: 0.13.1 => 0.13.1
    gatsby-plugin-federation: 2.5.0 => 2.5.0
    gatsby-plugin-image: 3.12.3 => 3.12.3
    gatsby-plugin-manifest: 5.12.3 => 5.12.3
    gatsby-plugin-offline: 6.12.3 => 6.12.3
    gatsby-plugin-preconnect: 1.4.0 => 1.4.0
    gatsby-plugin-robots-txt: 1.8.0 => 1.8.0
    gatsby-plugin-sharp: 5.12.3 => 5.12.3
    gatsby-plugin-sitemap: 6.12.3 => 6.12.3
    gatsby-plugin-styled-components: 6.12.0 => 6.12.0
    gatsby-source-filesystem: 5.12.1 => 5.12.1
    gatsby-transformer-sharp: 5.12.3 => 5.12.3

**Comment by syckki** [comment]
@moonmeister 

Yes, I did!

I am using `gatsby build --prefix-paths` in order to build with prefixPath. Right now I am serving my app with that configuration and with that minimal change. I would appreciate to you that you can reproduce my issue following my instrucction. 

Include the `gatsby build --prefix-paths` in the script,  since I omite mentioned it before.

Note: in fact `gatsby serve  --prefix-paths` has problems using SSR. And your plugin is better than gatsby serve

**Comment by moonmeister** [comment]
The many problems with `gatsby serve` are why this plugin exists.

Okay, I'll try to find some time to look at this.

 From my current understanding your current solution shouldn't be correct, the assumption is...if you have a prefix, the non-prefixed path is probably an entirely different server and thus wouldn't be able to handle these routes.

**Comment by moonmeister** [comment]
Okay, confirmed. I understand what's happening. `potentialPagePath` seems like the correct move since we already have that. I'm happy to merge a PR on this if you can get that submitted.

**Comment by syckki** [comment]
Thank you for the confirmation! I agree with proceeding with "potentialPagePath". I plan to submit the Pull Request, but I'll do so after the Christmas holidays. I hope you have a wonderful holiday season with your loved ones as well. 🎄☃️

**Comment by moonmeister** [comment]
Deprecating Package. See: #495 for more info.
