### ISSUE TITLE
bug(gatsby-source-strapi): GraphQL fragment queries only work if all possible components of a dynamic zone are actually used in the current content

### ISSUE THREAD

**Issue by paulwellnerbou** [gatsby-uc/plugins#475]
## Describe the bug

The GraphQL API exposed by Gatsby considers only existing content. This leads to errors when building/running the project if the current content is not using a certain component in a dynamic zone. But is has to be mentioned/queried to handle it.

## To Reproduce

1. Create a new Gatsby/Strapi project with the given template (see https://github.com/strapi/starters-and-templates/tree/main/packages/starters/gatsby-blog)
2. Remove all components of (e.g.) "slider" from all example articles
3. Try to build/run your project

You will get this error:

```
  GraphQLError: Unknown type "STRAPI__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTSTRAPI__COMPONENT_SHARED_SLIDERUnion". Did you mean "STR
  API__COMPONENT_SHARED_MEDIASTRAPI__COMPONENT_SHARED_QUOTESTRAPI__COMPONENT_SHARED_RICH_TEXTUnion"?
```

## Expected behavior

Project should build and run like before, just without the image slider components

## System Info

See versions in https://github.com/strapi/starters-and-templates/tree/main/packages/starters/gatsby-blog

I am not completely sure where this bug is supposed to be addressed. Am I doing something wrong? Is the example starter buggy? Is it something in strapi? Or in Gatsby?

**Comment by laurenskling** [comment]
I even manually add all my types, the same shape they would be created if they were filled. 🥲 
So yes, this is documented. We know.
