### ISSUE TITLE
bug(gatsby-source-strapi): 400 Error Type with QueryParams

### ISSUE THREAD

**Issue by thatnewwen** [gatsby-uc/plugins#496]
## Describe the bug

Recently upgraded to Strapi 5, gatsby-source-strapi is no longer working. Getting a 400 error for a Single Type with Query Params set: 

`Failed to fetch data from Strapi /api/global with
{"method":"GET","url":"/api/global","params":{"populate":{"favicon":"*","headerImage":"*","defaultSeo":{"populate":"*"}}},"paramsSerializer":{}} Request
failed with status code 400`

If I remove Global, it gives me a 400 error for /api/pages. If I remove that, then it seems to go through, so not all collections are having issues, seems to be the ones that have Query Params set maybe?

## To Reproduce

I'm not sure, maybe just certain nested queries are causing issues?

## Expected behavior

gastby-source-strapi should still work after Strapi upgrade.

## System Info

Here is my config:

```
const strapiConfig = {
  version: 5,
  apiURL: process.env.STRAPI_API_URL,
  accessToken: process.env.STRAPI_TOKEN,
  collectionTypes: [
    {
      singularName: "profile",
      queryParams: {
        populate: {
          workSamples: {
            populate: "*",
          },
          disciplines: {
            populate: "*",
          },
          descriptors: {
            populate: "*",
          },
          profilePicture: {
            populate: "*",
          },
        },
      },
    },
    {
      singularName: "author",
    },
    {
      singularName: "category",
    },
    {
      singularName: "resource-tag",
    },
    {
      singularName: "testimonial",
    },
    {
      singularName: "discipline",
    },
    {
      singularName: "work-sample-discipline",
    },
    {
      singularName: "discipline-category",
    },
    {
      singularName: "descriptor",
    },
    {
      singularName: "descriptor-category",
    },
    {
      singularName: "resource",
    },
    {
      singularName: "page",
      queryParams: {
        populate: {
          coverImage: "*",
          image: "*",
          blocks: {
            populate: {
              image: "*",
              qa: "*",
            },
          },
          sideBlocks: {
            populate: {
              image: "*",
              qa: "*",
            },
          },
        },
      },
    },
  ],
  singleTypes: [
    {
      singularName: "global",
      queryParams: {
        populate: {
          favicon: "*",
          headerImage: "*",
          defaultSeo: {
            populate: "*",
          },
        },
      },
    },
  ],
}
```

**Comment by aprat-mentaia** [comment]
I had the same problem. The plugin documentation seems to be bad for the media type field.
In the Strapi documentation ([popular-select](https://docs.strapi.io/dev-docs/api/rest/populate-select)), the query is:
```
{
  populate: {
    headerImage: {
      fields: ['name', 'url'],
    },
  },
}
```
So for your global type, you should try:
```
{
  singularName: "global",
  queryParams: {
    populate: {
      favicon: {
        fields: ['*'],
      },
      headerImage: {
        fields: ['*'],
      },
      defaultSeo: {
        populate: "*",
      },
    },
  },
}
```

**Comment by thatnewwen** [comment]
@aprat-mentaia thanks so much for the suggestion! the fields really helped with the media queries...unfortunately, it doesn't seem to fix the issue with populating dynamic zones (blocks, sideBlocks) or components (defaultSeo). For example, defaultSeo has an image object on the component itself, and it doesn't seem to pull through...

Any advice? Thanks so much! You are a life saver!

**Comment by aprat-mentaia** [comment]
For me, this code:
```
defaultSeo: {
  populate: "*",
},
```
gets all attributes, including the image object.
But if you want only the image object ([populate-several-levels-deep-for-specific-relations](https://docs.strapi.io/dev-docs/api/rest/guides/understanding-populate#populate-several-levels-deep-for-specific-relations)), you can try:
```
{
  singularName: "global",
  queryParams: {
    populate: {
      favicon: {
        fields: ['*'],
      },
      headerImage: {
        fields: ['*'],
      },
      defaultSeo: {
        populate: ['image'],
      },
    },
  },
}
```

**Comment by thatnewwen** [comment]
I ended up needing to config my collection like this to pull in nested dynamic zones:

```
{
      singularName: "page",
      queryParams: {
        populate: {
          coverImage: {
            populate: "*"
          },
          sideBlocks: {
            populate: "*"
          },
          blocks: {
            populate: "*"
          },
        }
      }
    },
    ```
    
    where blocks and sideBlocks are dynamic zones. Thanks for the support!
